import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {" "}
        <div className=" size-[400px] top-[50%]  rounded-full bg-radial-[#FB00FF_50%,#5E00FF_92%] blur-2xl absolute"></div>
        {children}
        <div className=" size-[400px] left-[80%] top-[20%] rounded-full bg-radial-[#FB00FF_50%,#5E00FF_92%] blur-2xl absolute"></div>
      </body>
    </html>
  );
}
